"""
Run C — DPO (Direct Preference Optimization) fine-tuning.

Builds on the QLoRA checkpoint (Run B) and applies preference learning
using TRL's DPOTrainer. DPO replaces RLHF — no reward model needed.

DPO preference pairs are constructed from the CUAD test set:
  - 'chosen': ground-truth clause text (correct extraction)
  - 'rejected': a degraded version (incomplete, hallucinated, or wrong)

We auto-generate rejected responses in three categories:
  1. Truncated: cuts the answer midway
  2. Hallucinated date/party: replaces real entities with plausible fakes
  3. Wrong clause: uses a different clause type's answer

This creates a realistic preference dataset without human annotation.

Usage:
    python -m training.train_dpo
"""

from __future__ import annotations

import json
import logging
import random
import re
import sys
import time
from pathlib import Path

import mlflow

# `datasets` (pyarrow) MUST precede `torch` — see note in train_lora.py.
from datasets import Dataset

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import DPOConfig, DPOTrainer

from config import (
    BASE_MODEL_ID,
    CHECKPOINTS,
    DATA_PROCESSED,
    DPO_CONFIG,
    DPO_TRAINING_ARGS,
    HF_TOKEN,
    MLFLOW_TRACKING_URI,
    QLORA_BNB_CONFIG,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Preference pair construction
# ---------------------------------------------------------------------------


def build_preference_dataset(samples: list[dict]) -> list[dict]:
    """
    Build DPO preference pairs from CUAD samples.

    Each pair has:
        prompt   : the instruction (system + user turns formatted as text)
        chosen   : the correct clause extraction
        rejected : a degraded version generated by one of 3 strategies
    """
    rng = random.Random(42)
    pairs = []

    # Build a lookup of answers by clause type for cross-clause rejection
    by_clause: dict[str, list[str]] = {}
    for s in samples:
        by_clause.setdefault(s["clause_type"], []).append(s["answer"])

    for sample in samples:
        prompt = sample.get("prompt", "")
        chosen = sample["answer"]

        if not chosen or chosen.startswith("No "):
            # Skip absent clauses — no good chosen response to prefer
            continue

        # Pick rejection strategy randomly
        strategy = rng.choice(["truncate", "hallucinate", "wrong_clause"])

        if strategy == "truncate":
            words = chosen.split()
            if len(words) > 10:
                cut = rng.randint(len(words) // 4, len(words) // 2)
                rejected = " ".join(words[:cut]) + "... [incomplete]"
            else:
                rejected = "No relevant clause found."

        elif strategy == "hallucinate":
            # Replace dates and party names with plausible fakes
            rejected = _hallucinate_entities(chosen, rng)

        elif strategy == "wrong_clause":
            # Use a different clause type's answer as the rejection
            other_clauses = [c for c in by_clause if c != sample["clause_type"]]
            if other_clauses:
                wrong_clause = rng.choice(other_clauses)
                candidates = by_clause[wrong_clause]
                rejected = rng.choice(candidates) if candidates else "Not applicable."
            else:
                rejected = "This clause is not present in the agreement."

        pairs.append(
            {
                "prompt": prompt,
                "chosen": chosen,
                "rejected": rejected,
            }
        )

    log.info(f"Built {len(pairs)} DPO preference pairs")
    return pairs


def _hallucinate_entities(text: str, rng: random.Random) -> str:
    """Replace dates and company names with plausible fakes."""
    # Replace years
    fake_years = ["2019", "2021", "2022", "2023"]
    text = re.sub(r"\b(20\d{2})\b", lambda m: rng.choice(fake_years), text)

    # Replace party references
    fake_parties = [
        "Apex Technologies Inc.",
        "BlueStar Holdings LLC",
        "Meridian Partners Corp.",
        "Nexus Solutions Ltd.",
    ]
    text = re.sub(
        r"\b([A-Z][a-z]+ (Inc\.|LLC|Corp\.|Ltd\.|Co\.))",
        lambda m: rng.choice(fake_parties),
        text,
    )

    return text


# ---------------------------------------------------------------------------
# Main DPO training
# ---------------------------------------------------------------------------


def run_dpo(qlora_checkpoint: str | None = None) -> str:
    """
    Fine-tune with DPO on top of the QLoRA checkpoint.

    Parameters
    ----------
    qlora_checkpoint : str | None
        Path to the QLoRA checkpoint. Defaults to config value.
    """
    if qlora_checkpoint is None:
        qlora_checkpoint = str(CHECKPOINTS / "run_b_qlora")

    ckpt_path = Path(qlora_checkpoint)
    if not ckpt_path.exists():
        log.error(f"QLoRA checkpoint not found: {qlora_checkpoint}")
        log.error("Run: python -m training.train_qlora first.")
        sys.exit(1)

    # Load preference dataset from the val split
    val_path = DATA_PROCESSED / "val.json"
    if not val_path.exists():
        log.error("Processed data not found. Run: python -m data.pipeline first.")
        sys.exit(1)

    val_data = json.loads(val_path.read_text(encoding="utf-8"))
    preference_pairs = build_preference_dataset(val_data)

    if not preference_pairs:
        log.error("No preference pairs built. Check val split.")
        sys.exit(1)

    dpo_dataset = Dataset.from_list(preference_pairs)

    # Configure MLflow
    mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
    mlflow.set_experiment("cuad-llama-finetuning")

    with mlflow.start_run(run_name=DPO_TRAINING_ARGS["run_name"]):
        mlflow.log_params(
            {
                "base_model": BASE_MODEL_ID,
                "sft_checkpoint": qlora_checkpoint,
                "dpo_beta": DPO_CONFIG["beta"],
                "dpo_loss_type": DPO_CONFIG["loss_type"],
                "preference_pairs": len(preference_pairs),
                "learning_rate": DPO_TRAINING_ARGS["learning_rate"],
            }
        )

        # Load base model in 4-bit
        login_kwargs = {"token": HF_TOKEN} if HF_TOKEN else {}
        from transformers import BitsAndBytesConfig

        bnb_config = BitsAndBytesConfig(
            load_in_4bit=QLORA_BNB_CONFIG["load_in_4bit"],
            bnb_4bit_quant_type=QLORA_BNB_CONFIG["bnb_4bit_quant_type"],
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_use_double_quant=QLORA_BNB_CONFIG["bnb_4bit_use_double_quant"],
        )

        base_model = AutoModelForCausalLM.from_pretrained(
            BASE_MODEL_ID,
            quantization_config=bnb_config,
            device_map="auto",
            trust_remote_code=True,
            **login_kwargs,
        )

        # Load LoRA adapters from QLoRA checkpoint
        model = PeftModel.from_pretrained(
            base_model,
            qlora_checkpoint,
            is_trainable=True,
        )
        model.config.use_cache = False

        # No explicit reference model: with a PEFT/LoRA policy, TRL computes the
        # DPO reference log-probs by temporarily disabling the adapters on the
        # same base model. This halves VRAM vs. loading a second frozen copy —
        # essential on an 8GB GPU.

        tokenizer = AutoTokenizer.from_pretrained(
            BASE_MODEL_ID,
            trust_remote_code=True,
            **login_kwargs,
        )
        tokenizer.pad_token = tokenizer.eos_token
        tokenizer.padding_side = "right"

        # DPO training config
        dpo_args = DPOConfig(
            output_dir=DPO_TRAINING_ARGS["output_dir"],
            num_train_epochs=DPO_TRAINING_ARGS["num_train_epochs"],
            per_device_train_batch_size=DPO_TRAINING_ARGS[
                "per_device_train_batch_size"
            ],
            gradient_accumulation_steps=DPO_TRAINING_ARGS[
                "gradient_accumulation_steps"
            ],
            learning_rate=DPO_TRAINING_ARGS["learning_rate"],
            bf16=DPO_TRAINING_ARGS["bf16"],
            logging_steps=DPO_TRAINING_ARGS["logging_steps"],
            save_steps=DPO_TRAINING_ARGS["save_steps"],
            save_total_limit=DPO_TRAINING_ARGS["save_total_limit"],
            report_to="none",
            warmup_ratio=DPO_TRAINING_ARGS["warmup_ratio"],
            beta=DPO_CONFIG["beta"],
            max_length=DPO_CONFIG["max_length"],
            loss_type=DPO_CONFIG["loss_type"],
        )

        trainer = DPOTrainer(
            model=model,
            ref_model=None,  # PEFT policy: TRL disables adapters for the reference
            args=dpo_args,
            train_dataset=dpo_dataset,
            processing_class=tokenizer,  # TRL 1.x renamed tokenizer -> processing_class
        )

        log.info("Starting DPO training...")
        start = time.time()
        train_result = trainer.train()
        elapsed = time.time() - start

        mlflow.log_metrics(
            {
                "dpo_train_loss": train_result.training_loss,
                "dpo_runtime_s": elapsed,
            }
        )

        output_dir = DPO_TRAINING_ARGS["output_dir"]
        trainer.save_model(output_dir)
        tokenizer.save_pretrained(output_dir)
        log.info(f"DPO model saved to {output_dir}")
        mlflow.log_artifact(output_dir)

    return output_dir


if __name__ == "__main__":
    run_dpo()
